### ISSUE TITLE
variant.h: No such file or directory (STM32F030C6)

### ISSUE THREAD

**Issue by mrdROb** [maxgerhardt/pio-f030-test#1]
Trying to make your code running with Platformio on VSCode. Getting this error:

`C:\Users\dROb\.platformio\packages\framework-arduinoststm32\system\STM32F0xx/stm32f0xx_hal_conf.h:4:10: fatal error: variant.h: No such file or directory`

Can you please help? 
There is almost no information on STM32F030Cxxx microcontrollers with PIO and this code is the only hope :)

**Comment by mrdROb** [comment]
Looks like my issue was because my platformio was sticking to the extremely old STSTM32 platform (6.1.1).  Forced to use the new 18.0.0 and voila.
P.S. The board definition in the project has wrong flash (16k instead of 32k)
P.P.S. The 18,0.0 now does not like the russian names in the path. But since it is 2024 it is understandable...

**Comment by maxgerhardt** [comment]
Fixed in d40853d637b2c7655681dba9d362d8d51b94f86c and 8304f72dcf8b768277455226b60cbf7ceb182f9f
